# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0005_person_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Invoice',
            field=models.FileField(default=None, upload_to=b''),
        ),
    ]
