# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0006_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Invoice',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
