# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-05 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0009_auto_20170803_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='person',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
