# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0012_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Text',
            field=models.TextField(default=b'', max_length=500),
        ),
    ]
