# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0013_order_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_model.Order')),
            ],
        ),
    ]
